// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Models.CodeFirst;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116001750_ImplementacionRelacionNaNCodigoBarraConProducto")]
    partial class ImplementacionRelacionNaNCodigoBarraConProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Models.CodeFirst.Categoria", b =>
                {
                    b.Property<short>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("src.Models.CodeFirst.CodigoBarra", b =>
                {
                    b.Property<short>("IdCodigoBarra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_codigo_barra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCodigoBarra"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_barra");

                    b.HasKey("IdCodigoBarra");

                    b.ToTable("codigo_barra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.CondicionDePago", b =>
                {
                    b.Property<short>("IdCondicionPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCondicionPago"));

                    b.Property<short>("DiasPago")
                        .HasColumnType("smallint")
                        .HasColumnName("dias_pago");

                    b.HasKey("IdCondicionPago")
                        .HasName("condicion_pago_pkey");

                    b.ToTable("condicion_pago", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Property<short>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdDomicilio"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<short>("IdProvincia")
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.HasKey("IdDomicilio")
                        .HasName("domicilio_pkey");

                    b.HasIndex("IdProvincia");

                    b.ToTable("domicilio", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Grupo", b =>
                {
                    b.Property<short>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGrupo");

                    b.ToTable("grupo");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisoPermiso", b =>
                {
                    b.Property<short>("IdGrupoPermiso")
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdGrupoPermiso", "IdPermiso")
                        .HasName("grupo_permiso_permiso_pkey");

                    b.HasIndex("IdPermiso");

                    b.ToTable("grupo_permiso_permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisos", b =>
                {
                    b.Property<short>("IdGrupoPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdGrupoPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGrupoPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("unq_gpm");

                    b.ToTable("grupo_permisos", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.NovedadesProveedor", b =>
                {
                    b.Property<int>("IdNovedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_novedad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNovedad"));

                    b.Property<string>("CodigoBarraExterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra_externo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_importacion");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NombreSugerido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_sugerido");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_sugerido");

                    b.Property<short?>("ProductoIdProducto")
                        .HasColumnType("smallint");

                    b.HasKey("IdNovedad");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("novedades_proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("unq_pm");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Producto", b =>
                {
                    b.Property<short>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<int>("StockTotal")
                        .HasColumnType("integer")
                        .HasColumnName("stock_total");

                    b.HasKey("IdProducto");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCategoria", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdCategoria")
                        .HasColumnType("smallint")
                        .HasColumnName("id_categoria");

                    b.HasKey("IdProducto", "IdCategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("producto_categoria");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoBarra", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdCodigoBarra")
                        .HasColumnType("smallint")
                        .HasColumnName("id_codigo_barra");

                    b.HasKey("IdProducto", "IdCodigoBarra");

                    b.HasIndex("IdCodigoBarra");

                    b.ToTable("producto_codigo_barra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoExterno", b =>
                {
                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("CodigoBarraProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra_proveedor");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.HasKey("IdProveedor", "CodigoBarraProveedor");

                    b.HasIndex("IdProducto");

                    b.ToTable("producto_codigo_externo");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoGrupo", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdGrupo")
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo");

                    b.HasKey("IdProducto", "IdGrupo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("producto_grupo");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoProveedor", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int>("StockAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("stock_asignado");

                    b.HasKey("IdProducto", "IdProveedor");

                    b.HasIndex("IdProveedor");

                    b.ToTable("producto_proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.Property<short>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit");

                    b.Property<short>("IdCondicionPagoHabitual")
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago_habitual");

                    b.Property<short>("IdDomicilio")
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    b.Property<string>("PersonaResponsable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("persona_responsable");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Saldo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("saldo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("proveedor_pkey");

                    b.HasIndex("IdCondicionPagoHabitual");

                    b.HasIndex("IdDomicilio");

                    b.HasIndex(new[] { "Cuit" }, "unq_cuit")
                        .IsUnique();

                    b.HasIndex(new[] { "RazonSocial" }, "unq_razon")
                        .IsUnique();

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Property<short>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia")
                        .HasName("provincia_pkey");

                    b.HasIndex(new[] { "IdProvincia" }, "unq_prov")
                        .IsUnique();

                    b.ToTable("provincia");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Usuario", b =>
                {
                    b.Property<short>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioGrupoPermisos", b =>
                {
                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    b.Property<short>("IdGrupoPermiso")
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    b.HasKey("IdUsuario", "IdGrupoPermiso")
                        .HasName("usuario_grupo_permisos_pkey");

                    b.HasIndex("IdGrupoPermiso");

                    b.ToTable("usuario_grupo_permisos", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioPermiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint");

                    b.HasKey("IdPermiso", "IdUsuario")
                        .HasName("usuario_permiso_pkey");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.ToTable("contado", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.Property<short>("Cuotas")
                        .HasColumnType("smallint")
                        .HasColumnName("cuotas");

                    b.Property<decimal>("InteresPorcentual")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("interes_porcentual");

                    b.ToTable("cuota", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Provincia", "IdProvinciaNavigation")
                        .WithMany("Domicilios")
                        .HasForeignKey("IdProvincia")
                        .IsRequired()
                        .HasConstraintName("direccion_id_provincia_fkey");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisoPermiso", b =>
                {
                    b.HasOne("src.Models.CodeFirst.GrupoPermisos", "GrupoPermiso")
                        .WithMany("GruposPermisosPermisos")
                        .HasForeignKey("IdGrupoPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gpp_id_grupo_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Permiso", "Permiso")
                        .WithMany("GruposPermisosPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gpp_id_permiso_fkey");

                    b.Navigation("GrupoPermiso");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("src.Models.CodeFirst.NovedadesProveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", null)
                        .WithMany("Novedades")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCategoria", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Categoria", "Categoria")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoBarra", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CodigoBarra", "CodigoBarra")
                        .WithMany("ProductosCodigosBarras")
                        .HasForeignKey("IdCodigoBarra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductoCodigoBarras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoBarra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoExterno", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoGrupo", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Grupo", "Grupo")
                        .WithMany("ProductosGrupos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductosGrupos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoProveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductosProveedores")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany("ProductosProveedores")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", "IdCondicionPagoHabitualNavigation")
                        .WithMany()
                        .HasForeignKey("IdCondicionPagoHabitual")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_condicion_pago_habitual_fkey");

                    b.HasOne("src.Models.CodeFirst.Domicilio", "IdDomicilioNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdDomicilio")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_domicilio_fkey");

                    b.Navigation("IdCondicionPagoHabitualNavigation");

                    b.Navigation("IdDomicilioNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioGrupoPermisos", b =>
                {
                    b.HasOne("src.Models.CodeFirst.GrupoPermisos", "GrupoPermiso")
                        .WithMany("UsuariosGruposPermisos")
                        .HasForeignKey("IdGrupoPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ugp_id_grupo_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany("UsuariosGruposPermisos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ugp_id_usuario_fkey");

                    b.Navigation("GrupoPermiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioPermiso", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Permiso", "Permiso")
                        .WithMany("UsuariosPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_permiso_id_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany("UsuariosPermisos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_permiso_id_usuario_fkey");

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Contado", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Cuota", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Categoria", b =>
                {
                    b.Navigation("ProductosCategorias");
                });

            modelBuilder.Entity("src.Models.CodeFirst.CodigoBarra", b =>
                {
                    b.Navigation("ProductosCodigosBarras");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Grupo", b =>
                {
                    b.Navigation("ProductosGrupos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisos", b =>
                {
                    b.Navigation("GruposPermisosPermisos");

                    b.Navigation("UsuariosGruposPermisos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Permiso", b =>
                {
                    b.Navigation("GruposPermisosPermisos");

                    b.Navigation("UsuariosPermisos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Producto", b =>
                {
                    b.Navigation("Novedades");

                    b.Navigation("ProductoCodigoBarras");

                    b.Navigation("ProductosCategorias");

                    b.Navigation("ProductosGrupos");

                    b.Navigation("ProductosProveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.Navigation("ProductosProveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Navigation("Domicilios");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Usuario", b =>
                {
                    b.Navigation("UsuariosGruposPermisos");

                    b.Navigation("UsuariosPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
