// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Models.CodeFirst;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024061203_AgregaCongAutoIncrementalCondicionPAgo")]
    partial class AgregaCongAutoIncrementalCondicionPAgo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Models.CodeFirst.CondicionDePago", b =>
                {
                    b.Property<short>("IdCondicionPago")
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago");

                    b.Property<short>("DiasPago")
                        .HasColumnType("smallint")
                        .HasColumnName("dias_pago");

                    b.HasKey("IdCondicionPago")
                        .HasName("condicion_pago_pkey");

                    b.ToTable("condicion_pago", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Property<short>("IdDomicilio")
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<short>("IdProvincia")
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.HasKey("IdDomicilio")
                        .HasName("domicilio_pkey");

                    b.HasIndex("IdProvincia");

                    b.ToTable("domicilio", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.Property<short>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit");

                    b.Property<short>("IdCondicionPagoHabitual")
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago_habitual");

                    b.Property<short>("IdDomicilio")
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    b.Property<string>("PersonaResponsable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("persona_responsable");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Saldo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("saldo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("proveedor_pkey");

                    b.HasIndex("IdCondicionPagoHabitual");

                    b.HasIndex("IdDomicilio");

                    b.HasIndex(new[] { "Cuit" }, "unq_cuit")
                        .IsUnique();

                    b.HasIndex(new[] { "RazonSocial" }, "unq_razon")
                        .IsUnique();

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Property<short>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia")
                        .HasName("provincia_pkey");

                    b.HasIndex(new[] { "IdProvincia" }, "unq_prov")
                        .IsUnique();

                    b.ToTable("provincia");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Usuario", b =>
                {
                    b.Property<short>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.ToTable("contado", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.Property<short>("Cuotas")
                        .HasColumnType("smallint")
                        .HasColumnName("cuotas");

                    b.Property<decimal>("InteresPorcentual")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("interes_porcentual");

                    b.ToTable("cuota", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Provincia", "IdProvinciaNavigation")
                        .WithMany("Domicilios")
                        .HasForeignKey("IdProvincia")
                        .IsRequired()
                        .HasConstraintName("direccion_id_provincia_fkey");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", "IdCondicionPagoHabitualNavigation")
                        .WithMany()
                        .HasForeignKey("IdCondicionPagoHabitual")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_condicion_pago_habitual_fkey");

                    b.HasOne("src.Models.CodeFirst.Domicilio", "IdDomicilioNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdDomicilio")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_domicilio_fkey");

                    b.Navigation("IdCondicionPagoHabitualNavigation");

                    b.Navigation("IdDomicilioNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Contado", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Cuota", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Navigation("Domicilios");
                });
#pragma warning restore 612, 618
        }
    }
}
