// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using src.Models.CodeFirst;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("src.Models.CodeFirst.Auditoria.CompraAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompra")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("auditoria_compras");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Categoria", b =>
                {
                    b.Property<short>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<short>("IdFamilia")
                        .HasColumnType("smallint")
                        .HasColumnName("id_familia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdFamilia");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("src.Models.CodeFirst.CodigoBarra", b =>
                {
                    b.Property<short>("IdCodigoBarra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_codigo_barra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCodigoBarra"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_barra");

                    b.HasKey("IdCodigoBarra");

                    b.ToTable("codigo_barra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Compra", b =>
                {
                    b.Property<short>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCompra"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_compra");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("compra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_comprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComprobante"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdFacturaReferencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura_referencia");

                    b.Property<short>("IdMotivo")
                        .HasColumnType("smallint")
                        .HasColumnName("id_motivo");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_comprobante");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("IdComprobante");

                    b.HasIndex("IdFacturaReferencia");

                    b.HasIndex("IdMotivo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("comprobante", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("src.Models.CodeFirst.CondicionDePago", b =>
                {
                    b.Property<short>("IdCondicionPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdCondicionPago"));

                    b.Property<short>("DiasPago")
                        .HasColumnType("smallint")
                        .HasColumnName("dias_pago");

                    b.HasKey("IdCondicionPago")
                        .HasName("condicion_pago_pkey");

                    b.ToTable("condicion_pago", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Deposito", b =>
                {
                    b.Property<int>("IdDeposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_deposito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeposito"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<short>("IdDireccion")
                        .HasColumnType("smallint")
                        .HasColumnName("id_direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdDeposito");

                    b.HasIndex("IdDireccion");

                    b.ToTable("deposito");
                });

            modelBuilder.Entity("src.Models.CodeFirst.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleCompra"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<short>("IdCompra")
                        .HasColumnType("smallint")
                        .HasColumnName("id_compra");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioPactado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_pactado");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_compra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_bruto");

                    b.Property<decimal>("PrecioNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_neto");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_factura");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Property<short>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdDomicilio"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calle");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<short>("IdProvincia")
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.HasKey("IdDomicilio")
                        .HasName("domicilio_pkey");

                    b.HasIndex("IdProvincia");

                    b.ToTable("domicilio", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Estante", b =>
                {
                    b.Property<int>("IdEstante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstante"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("IdDeposito")
                        .HasColumnType("integer")
                        .HasColumnName("id_deposito");

                    b.Property<string>("NumeroEstante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_estante");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<bool>("TieneEspacio")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_espacio");

                    b.HasKey("IdEstante");

                    b.HasIndex("IdDeposito");

                    b.ToTable("estante");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<short>("IdCompra")
                        .HasColumnType("smallint")
                        .HasColumnName("id_compra");

                    b.Property<short>("IdCondicionPagoUsada")
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago_usada");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_factura");

                    b.Property<bool>("Pagada")
                        .HasColumnType("boolean")
                        .HasColumnName("pagada");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.Property<decimal>("TotalFacturado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_facturado");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdCondicionPagoUsada");

                    b.HasIndex("IdProveedor");

                    b.ToTable("factura");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Familia", b =>
                {
                    b.Property<short>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_familia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdFamilia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdFamilia");

                    b.ToTable("familia");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Fila", b =>
                {
                    b.Property<int>("IdFila")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fila");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFila"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("IdEstante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estante");

                    b.Property<string>("NFila")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("n_fila");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<bool>("TieneEspacio")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_espacio");

                    b.HasKey("IdFila");

                    b.HasIndex("IdEstante");

                    b.ToTable("fila");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisoPermiso", b =>
                {
                    b.Property<short>("IdGrupoPermiso")
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdGrupoPermiso", "IdPermiso")
                        .HasName("grupo_permiso_permiso_pkey");

                    b.HasIndex("IdPermiso");

                    b.ToTable("grupo_permiso_permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisos", b =>
                {
                    b.Property<short>("IdGrupoPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdGrupoPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGrupoPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("unq_gpm");

                    b.ToTable("grupo_permisos", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.MotivoComprobante", b =>
                {
                    b.Property<short>("IdMotivoComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_motivo_comprobante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdMotivoComprobante"));

                    b.Property<string>("ClaseComprobante")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("clase_comprobante");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdMotivoComprobante");

                    b.ToTable("motivo_comprobante");
                });

            modelBuilder.Entity("src.Models.CodeFirst.MovimientoStock", b =>
                {
                    b.Property<int>("IdMovimientoStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento_stock");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimientoStock"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<int?>("IdFilaDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_fila_destino");

                    b.Property<int?>("IdFilaOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_fila_origen");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    b.Property<short?>("ProductoIdProducto")
                        .HasColumnType("smallint");

                    b.HasKey("IdMovimientoStock");

                    b.HasIndex("IdFilaDestino");

                    b.HasIndex("IdFilaOrigen");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("movimiento_stock", t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosStock_Cantidad", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("src.Models.CodeFirst.NovedadesProveedor", b =>
                {
                    b.Property<int>("IdNovedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_novedad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNovedad"));

                    b.Property<string>("CodigoBarraExterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra_externo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_importacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<short?>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NombreSugerido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_sugerido");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioSugerido")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_sugerido");

                    b.Property<int>("StockSugerido")
                        .HasColumnType("integer")
                        .HasColumnName("stock_sugerido");

                    b.HasKey("IdNovedad");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("novedades_proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.OrdenPago", b =>
                {
                    b.Property<int>("IdOrdenPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_orden_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenPago"));

                    b.Property<bool>("Enviada")
                        .HasColumnType("boolean")
                        .HasColumnName("enviada");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_orden");

                    b.HasKey("IdOrdenPago")
                        .HasName("orden_pago_pkey");

                    b.HasIndex("IdProveedor");

                    b.ToTable("orden_pago", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.PagoDetalle", b =>
                {
                    b.Property<int>("IdOrdenPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_orden_pago");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<decimal>("MontoAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_aplicado");

                    b.HasKey("IdOrdenPago", "IdFactura");

                    b.HasIndex("IdFactura");

                    b.ToTable("pago_detalle", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("unq_pm");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Producto", b =>
                {
                    b.Property<short>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<int>("StockTotal")
                        .HasColumnType("integer")
                        .HasColumnName("stock_total");

                    b.HasKey("IdProducto");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCategoria", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdCategoria")
                        .HasColumnType("smallint")
                        .HasColumnName("id_categoria");

                    b.HasKey("IdProducto", "IdCategoria");

                    b.HasIndex("IdCategoria");

                    b.ToTable("producto_categoria");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoBarra", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdCodigoBarra")
                        .HasColumnType("smallint")
                        .HasColumnName("id_codigo_barra");

                    b.HasKey("IdProducto", "IdCodigoBarra");

                    b.HasIndex("IdCodigoBarra");

                    b.ToTable("producto_codigo_barra");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoExterno", b =>
                {
                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("CodigoBarraProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra_proveedor");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.HasKey("IdProveedor", "CodigoBarraProveedor");

                    b.HasIndex("IdProducto");

                    b.ToTable("producto_codigo_externo");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoProveedor", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<short>("IdProveedor")
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int>("StockAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("stock_asignado");

                    b.HasKey("IdProducto", "IdProveedor");

                    b.HasIndex("IdProveedor");

                    b.ToTable("producto_proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.Property<short>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit");

                    b.Property<short>("IdCondicionPagoHabitual")
                        .HasColumnType("smallint")
                        .HasColumnName("id_condicion_pago_habitual");

                    b.Property<short>("IdDomicilio")
                        .HasColumnType("smallint")
                        .HasColumnName("id_domicilio");

                    b.Property<string>("PersonaResponsable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("persona_responsable");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("razon_social");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("proveedor_pkey");

                    b.HasIndex("IdCondicionPagoHabitual");

                    b.HasIndex("IdDomicilio");

                    b.HasIndex(new[] { "Cuit" }, "unq_cuit")
                        .IsUnique();

                    b.HasIndex(new[] { "RazonSocial" }, "unq_razon")
                        .IsUnique();

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Property<short>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia")
                        .HasName("provincia_pkey");

                    b.HasIndex(new[] { "IdProvincia" }, "unq_prov")
                        .IsUnique();

                    b.ToTable("provincia");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UbicacionProducto", b =>
                {
                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdFila")
                        .HasColumnType("integer")
                        .HasColumnName("id_fila");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.HasKey("IdProducto", "IdFila");

                    b.HasIndex("IdFila");

                    b.ToTable("ubicacion_producto", t =>
                        {
                            t.HasCheckConstraint("CK_UbicacionProducto_Cantidad", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("src.Models.CodeFirst.Usuario", b =>
                {
                    b.Property<short>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("unq_correo");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("unq_identificacion");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioGrupoPermisos", b =>
                {
                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint")
                        .HasColumnName("id_usuario");

                    b.Property<short>("IdGrupoPermiso")
                        .HasColumnType("smallint")
                        .HasColumnName("id_grupo_permiso");

                    b.HasKey("IdUsuario", "IdGrupoPermiso")
                        .HasName("usuario_grupo_permisos_pkey");

                    b.HasIndex("IdGrupoPermiso");

                    b.ToTable("usuario_grupo_permisos", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioPermiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint");

                    b.HasKey("IdPermiso", "IdUsuario")
                        .HasName("usuario_permiso_pkey");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_permiso", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.NotaCredito", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.Comprobante");

                    b.ToTable("nota_credito", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.NotaDebito", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.Comprobante");

                    b.ToTable("nota_debito", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.ToTable("contado", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasBaseType("src.Models.CodeFirst.CondicionDePago");

                    b.Property<short>("Cuotas")
                        .HasColumnType("smallint")
                        .HasColumnName("cuotas");

                    b.Property<decimal>("InteresPorcentual")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("interes_porcentual");

                    b.ToTable("cuota", (string)null);
                });

            modelBuilder.Entity("src.Models.CodeFirst.Categoria", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Familia", "Familia")
                        .WithMany("Categorias")
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Compra", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Comprobante", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Factura", "FacturaOriginal")
                        .WithMany()
                        .HasForeignKey("IdFacturaReferencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.MotivoComprobante", "Motivo")
                        .WithMany()
                        .HasForeignKey("IdMotivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaOriginal");

                    b.Navigation("Motivo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Deposito", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Domicilio", "Direccion")
                        .WithMany()
                        .HasForeignKey("IdDireccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("src.Models.CodeFirst.DetalleCompra", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.DetalleFactura", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Provincia", "IdProvinciaNavigation")
                        .WithMany("Domicilios")
                        .HasForeignKey("IdProvincia")
                        .IsRequired()
                        .HasConstraintName("direccion_id_provincia_fkey");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Estante", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Deposito", "Deposito")
                        .WithMany("Estantes")
                        .HasForeignKey("IdDeposito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Factura", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Compra", "Compra")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.CondicionDePago", "CondicionPago")
                        .WithMany()
                        .HasForeignKey("IdCondicionPagoUsada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("CondicionPago");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Fila", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Estante", "Estante")
                        .WithMany("Filas")
                        .HasForeignKey("IdEstante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estante");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisoPermiso", b =>
                {
                    b.HasOne("src.Models.CodeFirst.GrupoPermisos", "GrupoPermiso")
                        .WithMany("GruposPermisosPermisos")
                        .HasForeignKey("IdGrupoPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gpp_id_grupo_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Permiso", "Permiso")
                        .WithMany("GruposPermisosPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gpp_id_permiso_fkey");

                    b.Navigation("GrupoPermiso");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("src.Models.CodeFirst.MovimientoStock", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Fila", "FilaDestino")
                        .WithMany()
                        .HasForeignKey("IdFilaDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("src.Models.CodeFirst.Fila", "FilaOrigen")
                        .WithMany()
                        .HasForeignKey("IdFilaOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoIdProducto");

                    b.Navigation("FilaDestino");

                    b.Navigation("FilaOrigen");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.NovedadesProveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("Novedades")
                        .HasForeignKey("IdProducto");

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.OrdenPago", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.PagoDetalle", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.OrdenPago", "OrdenPago")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrdenPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("OrdenPago");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCategoria", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Categoria", "Categoria")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoBarra", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CodigoBarra", "CodigoBarra")
                        .WithMany("ProductosCodigosBarras")
                        .HasForeignKey("IdCodigoBarra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductoCodigoBarras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoBarra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoCodigoExterno", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("CodigosBarrasExternos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany("CodigosBarrasExternos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.ProductoProveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("ProductosProveedores")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Proveedor", "Proveedor")
                        .WithMany("ProductosProveedores")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", "IdCondicionPagoHabitualNavigation")
                        .WithMany()
                        .HasForeignKey("IdCondicionPagoHabitual")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_condicion_pago_habitual_fkey");

                    b.HasOne("src.Models.CodeFirst.Domicilio", "IdDomicilioNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdDomicilio")
                        .IsRequired()
                        .HasConstraintName("proveedor_id_domicilio_fkey");

                    b.Navigation("IdCondicionPagoHabitualNavigation");

                    b.Navigation("IdDomicilioNavigation");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UbicacionProducto", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Fila", "Fila")
                        .WithMany("UbicacionesProductos")
                        .HasForeignKey("IdFila")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.Models.CodeFirst.Producto", "Producto")
                        .WithMany("UbicacionesProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fila");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioGrupoPermisos", b =>
                {
                    b.HasOne("src.Models.CodeFirst.GrupoPermisos", "GrupoPermiso")
                        .WithMany("UsuariosGruposPermisos")
                        .HasForeignKey("IdGrupoPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ugp_id_grupo_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany("UsuariosGruposPermisos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ugp_id_usuario_fkey");

                    b.Navigation("GrupoPermiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.UsuarioPermiso", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Permiso", "Permiso")
                        .WithMany("UsuariosPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_permiso_id_permiso_fkey");

                    b.HasOne("src.Models.CodeFirst.Usuario", "Usuario")
                        .WithMany("UsuariosPermisos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_permiso_id_usuario_fkey");

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("src.Models.CodeFirst.NotaCredito", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Comprobante", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.NotaCredito", "IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.NotaDebito", b =>
                {
                    b.HasOne("src.Models.CodeFirst.Comprobante", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.NotaDebito", "IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Contado", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Contado", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Cuota", b =>
                {
                    b.HasOne("src.Models.CodeFirst.CondicionDePago", null)
                        .WithOne()
                        .HasForeignKey("src.Models.CodeFirst.Cuota", "IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("src.Models.CodeFirst.Categoria", b =>
                {
                    b.Navigation("ProductosCategorias");
                });

            modelBuilder.Entity("src.Models.CodeFirst.CodigoBarra", b =>
                {
                    b.Navigation("ProductosCodigosBarras");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Compra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Deposito", b =>
                {
                    b.Navigation("Estantes");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Domicilio", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Estante", b =>
                {
                    b.Navigation("Filas");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Familia", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Fila", b =>
                {
                    b.Navigation("UbicacionesProductos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.GrupoPermisos", b =>
                {
                    b.Navigation("GruposPermisosPermisos");

                    b.Navigation("UsuariosGruposPermisos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.OrdenPago", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Permiso", b =>
                {
                    b.Navigation("GruposPermisosPermisos");

                    b.Navigation("UsuariosPermisos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Producto", b =>
                {
                    b.Navigation("CodigosBarrasExternos");

                    b.Navigation("Movimientos");

                    b.Navigation("Novedades");

                    b.Navigation("ProductoCodigoBarras");

                    b.Navigation("ProductosCategorias");

                    b.Navigation("ProductosProveedores");

                    b.Navigation("UbicacionesProductos");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Proveedor", b =>
                {
                    b.Navigation("CodigosBarrasExternos");

                    b.Navigation("ProductosProveedores");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Provincia", b =>
                {
                    b.Navigation("Domicilios");
                });

            modelBuilder.Entity("src.Models.CodeFirst.Usuario", b =>
                {
                    b.Navigation("UsuariosGruposPermisos");

                    b.Navigation("UsuariosPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
